### ISSUE TITLE
New version from 3/8/20 (which is for some reason 1.0.12.jar) breaks with ".setConsumeCatalyst(false)"

### ISSUE THREAD

**Issue by Goldenlion5648** [TeamDman/Zen-Summoning#12]
When updating the mod, my script broke. Even when taking this out and no errors are given, the recipe does not work.

**Comment by TeamDman** [comment]
Somehow an old build got uploaded instead of the new one, my bad.
There _shouldn't_ be any effects from using an old build, but if there are some issues then try breaking and replacing the altar first.
[Proper build waiting for approval should be ready soon.](https://www.curseforge.com/minecraft/mc-mods/zen-summoning/files/2898177)
