### ISSUE TITLE
Items are not accepted by altar

### ISSUE THREAD

**Issue by Goldenlion5648** [TeamDman/Zen-Summoning#13]
The altar in the new version from 3/8/20 does not take items at all when right clicked

**Comment by TeamDman** [comment]
A bad version was accidentally published and has since been deleted from curseforge page. Sorry.
[The proper build will be available soon](https://www.curseforge.com/minecraft/mc-mods/zen-summoning/files/2898177)
Breaking and replacing the altar after updating and after any changes to scripts should fix the issue of not accepting items, since the altar capacity is based off the known rituals when first placed, and is then saved to NBT.
