### ISSUE TITLE
Game Crash when summoning LittleMaid

### ISSUE THREAD

**Issue by nukesuke** [TeamDman/Zen-Summoning#28]
Here is my script :
https://pastebin.com/Phf1s0tJ

Summoning LittleMaid with a summoning item will crash the game.

Here is Crash Report :
https://pastebin.com/E3NW2CyM

Minecraft 1.12.2 Single
Forge - 14.23.5.2855

Here is Mod List :
CraftTweaker2-1.12-4.1.20.669
LittleMaidReengaged_FirisPatch-9.3.8.fp.058
LMLibrary-1.1.5
Zen Summoning-1.12-1.1.0

LittleMaidReengaged_FirisPatch-9.3.8.fp.058 download is here.
https://github.com/firis-games/LittleMaidReengagedFirisPatch/releases/tag/ver.fp.058

LMLibrary-1.1.5 download is here
https://github.com/firis-games/LittleMaidReengagedFirisPatch/releases/tag/ver.fp.055

LittleMaidAvatar and LittleMaidAppendPack are mods that only change the looks, so there is no problem if you don't install them.

**Comment by TeamDman** [comment]
Looks like I was deserializing NBT even if the data is empty.
Added a new `.mergeData()` method on MobInfo which will merge the given data with the mob's default data, rather than overwrite it which is the default behaviour if mergeData is not called.

I found the maid class if you wanna peek at their other NBT stuff I guess
https://github.com/Verclene/LittleMaidReengaged/blob/master/src/main/java/net/blacklab/lmr/entity/littlemaid/EntityLittleMaid.java#L1271

Should be available on latest build (1.3.5)
https://www.curseforge.com/minecraft/mc-mods/zen-summoning/files/3625247
